### ISSUE TITLE
Abililty to specify the camera container

### ISSUE THREAD

**Issue by stephanedemotte** [JamesMilnerUK/THREEAR#41] opened 2019-03-15 17:16 UTC
By default you inject the camera (<video>) in the document.

Could be cool to inject it in a div... or any dom element :)

**Comment by JamesMilnerUK** [comment] 2019-03-15 21:34
I think this is partly related to #31. I did have a branch where I allowed people to provide there own camera dom element, but the problem is that it has to be full screen to work correctly. If the div has to be full screen, at the moment it doesn't seem to make too much difference if the library generates the DOM element on the user does, because it will have to occupy the whole screen (`position: absolute` etc). Unfortunately from my brief experiments, fixing #31 isn't a simple task. 

This being said, I can see the advantage to being able to place it into a specific parent element, from a hierachical/flow perspective, even if it has to be full screen. Let me have a think about how this might work.

**Comment by JamesMilnerUK** [comment] 2019-03-16 19:26
@stephanedemotte I am going to close this as I think I resolved it in #45 :smile:

**Closed by JamesMilnerUK** 2019-03-16 19:26 UTC
Labels: enhancement
